# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: CI Pipeline
run-name: CI Pipeline
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Copy files into the build
      run: |-
        mkdir build
        rsync -av --exclude '.git' --exclude '.github' --exclude 'LICENSE' --exclude 'README.md' --exclude='*.sh' ./ build/
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build
  deploy_to_aws_s3_on_main_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v5
      with:
        name: build
        path: .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.S3_DEPLOY_ROLE }}
        aws-region: us-east-1
    - name: Upload File to S3
      run: |-
        aws s3 cp '.' 's3://me.cmdr2.org/carbon' --acl public-read --recursive
