name: deploy-to-s3
run-name: Generate and upload to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.PROD_DEPLOY_ROLE }}
        aws-region: us-east-1
    - name: Copy files to S3
      run: |
        aws s3 sync . "s3://me.cmdr2.org/carbon" --exclude ".git/*" --exclude ".github/*" --exclude "LICENSE" --exclude "README.md" --exclude "*.sh" --acl public-read
      shell: bash
