# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: CI Pipeline
run-name: CI Pipeline
on:
  push:
    branches:
    - main
jobs:
  deploy_to_aws_s3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.S3_DEPLOY_ROLE }}
        aws-region: us-east-1
    - name: Sync Files to S3
      run: |-
        aws s3 sync '.' 's3://me.cmdr2.org/carbon' --exclude '.git/*' --exclude '.github/*' --exclude 'LICENSE' --exclude 'README.md' --exclude '*.sh' --acl public-read
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main'
